/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ManageBookingsRouteImport } from './routes/manage-bookings'
import { Route as GpPreviewRouteImport } from './routes/gp-preview'
import { Route as BookMeetingsEventsRouteImport } from './routes/book-meetings-events'
import { Route as BookLeisureRouteImport } from './routes/book-leisure'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomingListBookingIdRouteImport } from './routes/rooming-list.$bookingId'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings.$bookingId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageBookingsRoute = ManageBookingsRouteImport.update({
  id: '/manage-bookings',
  path: '/manage-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const GpPreviewRoute = GpPreviewRouteImport.update({
  id: '/gp-preview',
  path: '/gp-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const BookMeetingsEventsRoute = BookMeetingsEventsRouteImport.update({
  id: '/book-meetings-events',
  path: '/book-meetings-events',
  getParentRoute: () => rootRouteImport,
} as any)
const BookLeisureRoute = BookLeisureRouteImport.update({
  id: '/book-leisure',
  path: '/book-leisure',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomingListBookingIdRoute = RoomingListBookingIdRouteImport.update({
  id: '/rooming-list/$bookingId',
  path: '/rooming-list/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/book-leisure': typeof BookLeisureRoute
  '/book-meetings-events': typeof BookMeetingsEventsRoute
  '/gp-preview': typeof GpPreviewRoute
  '/manage-bookings': typeof ManageBookingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/rooming-list/$bookingId': typeof RoomingListBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/book-leisure': typeof BookLeisureRoute
  '/book-meetings-events': typeof BookMeetingsEventsRoute
  '/gp-preview': typeof GpPreviewRoute
  '/manage-bookings': typeof ManageBookingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/rooming-list/$bookingId': typeof RoomingListBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/book-leisure': typeof BookLeisureRoute
  '/book-meetings-events': typeof BookMeetingsEventsRoute
  '/gp-preview': typeof GpPreviewRoute
  '/manage-bookings': typeof ManageBookingsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/rooming-list/$bookingId': typeof RoomingListBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/book-leisure'
    | '/book-meetings-events'
    | '/gp-preview'
    | '/manage-bookings'
    | '/reset-password'
    | '/bookings/$bookingId'
    | '/rooming-list/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/book-leisure'
    | '/book-meetings-events'
    | '/gp-preview'
    | '/manage-bookings'
    | '/reset-password'
    | '/bookings/$bookingId'
    | '/rooming-list/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/book-leisure'
    | '/book-meetings-events'
    | '/gp-preview'
    | '/manage-bookings'
    | '/reset-password'
    | '/bookings/$bookingId'
    | '/rooming-list/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  BookLeisureRoute: typeof BookLeisureRoute
  BookMeetingsEventsRoute: typeof BookMeetingsEventsRoute
  GpPreviewRoute: typeof GpPreviewRoute
  ManageBookingsRoute: typeof ManageBookingsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  BookingsBookingIdRoute: typeof BookingsBookingIdRoute
  RoomingListBookingIdRoute: typeof RoomingListBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-bookings': {
      id: '/manage-bookings'
      path: '/manage-bookings'
      fullPath: '/manage-bookings'
      preLoaderRoute: typeof ManageBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gp-preview': {
      id: '/gp-preview'
      path: '/gp-preview'
      fullPath: '/gp-preview'
      preLoaderRoute: typeof GpPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-meetings-events': {
      id: '/book-meetings-events'
      path: '/book-meetings-events'
      fullPath: '/book-meetings-events'
      preLoaderRoute: typeof BookMeetingsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-leisure': {
      id: '/book-leisure'
      path: '/book-leisure'
      fullPath: '/book-leisure'
      preLoaderRoute: typeof BookLeisureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooming-list/$bookingId': {
      id: '/rooming-list/$bookingId'
      path: '/rooming-list/$bookingId'
      fullPath: '/rooming-list/$bookingId'
      preLoaderRoute: typeof RoomingListBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  BookLeisureRoute: BookLeisureRoute,
  BookMeetingsEventsRoute: BookMeetingsEventsRoute,
  GpPreviewRoute: GpPreviewRoute,
  ManageBookingsRoute: ManageBookingsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  BookingsBookingIdRoute: BookingsBookingIdRoute,
  RoomingListBookingIdRoute: RoomingListBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
