/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BookLeisureRouteImport } from './routes/book-leisure'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookLeisureRequestRouteImport } from './routes/book-leisure.request'

const BookLeisureRoute = BookLeisureRouteImport.update({
  id: '/book-leisure',
  path: '/book-leisure',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookLeisureRequestRoute = BookLeisureRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => BookLeisureRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book-leisure': typeof BookLeisureRouteWithChildren
  '/book-leisure/request': typeof BookLeisureRequestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-leisure': typeof BookLeisureRouteWithChildren
  '/book-leisure/request': typeof BookLeisureRequestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book-leisure': typeof BookLeisureRouteWithChildren
  '/book-leisure/request': typeof BookLeisureRequestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/book-leisure' | '/book-leisure/request'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/book-leisure' | '/book-leisure/request'
  id: '__root__' | '/' | '/book-leisure' | '/book-leisure/request'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookLeisureRoute: typeof BookLeisureRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/book-leisure': {
      id: '/book-leisure'
      path: '/book-leisure'
      fullPath: '/book-leisure'
      preLoaderRoute: typeof BookLeisureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-leisure/request': {
      id: '/book-leisure/request'
      path: '/request'
      fullPath: '/book-leisure/request'
      preLoaderRoute: typeof BookLeisureRequestRouteImport
      parentRoute: typeof BookLeisureRoute
    }
  }
}

interface BookLeisureRouteChildren {
  BookLeisureRequestRoute: typeof BookLeisureRequestRoute
}

const BookLeisureRouteChildren: BookLeisureRouteChildren = {
  BookLeisureRequestRoute: BookLeisureRequestRoute,
}

const BookLeisureRouteWithChildren = BookLeisureRoute._addFileChildren(
  BookLeisureRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookLeisureRoute: BookLeisureRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
